version: '3.8'

services: 
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports: 
      - 8080:8080
    volumes: 
      - jenkins:/var/jenkins_home
    networks: 
      - bubble

  remote-host:
    container_name: remote-host
    image: remote-host
    build: 
      context: centOS7
    networks: 
      - bubble

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - bubble

volumes: 
  - jenkins:
  - mysql:

networks: 
  bubble: