version: '3.8'

services: 
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports: 
      - 8080:8080
    volumes: 
      - jenkins:/var/jenkins_home
    networks: 
      - bubble

volumes: 
  jenkins:

networks: 
  bubble: